name: Public Proxy Workflow

on: 
  workflow_dispatch:

jobs:
  trigger-private-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3

      - name: Trigger private workflow
        env:
          REPO_PAT: ${{ secrets.REPO_PAT }}
        run: |
          curl -X POST -H "Authorization: token $REPO_PAT" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/tfantas/my-private-repo/actions/workflows/private.yml/dispatches \
          -d '{"ref": "main"}'
